FROM openjdk:8-jdk-alpine
RUN apk update && apk add expect expect-dev && rm -rf /var/cache/apk/*
COPY ./target/jms-example-SNAPSHOT.jar /

CMD [ "sh", "-c", "unbuffer java -cp .:jms-example-SNAPSHOT.jar example.Producer Topic | tee output.log" ]
